export const safeSchoolSelect = {
  id: true,
  name: true,
  domain: true,
  verified: true,
  requiredHours: true,
  verificationStandard: true,
  serviceStartDate: true,
  serviceEndDate: true,
  allowSelfSubmission: true,
  requireOrgVerification: true,
  categoryHourCaps: true,
  allowJoinByCode: true,
  onboardingComplete: true,
  partnerInviteTemplate: true,
  zipCodes: true,
  address: true,
  city: true,
  state: true,
  zip: true,
  latitude: true,
  longitude: true,
  createdAt: true,
  updatedAt: true,
} as const;
